In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from bs4 import BeautifulSoup
import warnings
warnings.filterwarnings("ignore")
import requests

In [3]:
url="https://www.flipkart.com/search?q=refrigerator&sid=j9e,abm,hzg&as=on&as-show=on&as-pos=1&as-type=RECENT&as-searchtext=ref&requestId=c5770c84-ccd6-4072-b696-8e25ea970ead&suggestionId=refrigerator%7CRefrigerators&otracker=AS_QueryStore_OrganicAutoSuggest_%7BPOSITION%7D_3_na_na_na&isSearchQuery=true"

In [4]:
respones=requests.get(url)
respones

In [5]:
headers={"user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/147.0.0.0 Safari/537.36 Edg/147.0.0.0"}

In [6]:
responses=requests.get(url,headers=headers)
responses

In [7]:
pagecontent=responses.text

In [8]:
print(len(pagecontent))

767923

In [9]:
soup=BeautifulSoup(pagecontent)

In [10]:
pname=soup.find("div",attrs={"class":"RG5Slk"})
pname

In [11]:
productname=[]

for x in soup.find_all('div',attrs={'class':"RG5Slk"}):
    productname.append(x.text if x else np.nan)

for name in productname:
    print(name)

LG 185 L Direct Cool Single Door 2 Star Refrigerator with Base Drawer  with Chiller Tray, Works withou...
LG 185 L Direct Cool Single Door 2 Star Refrigerator with Base Drawer  with Chiller Tray, Works withou...
Godrej 180 L Direct Cool Single Door 1 Star Refrigerator
Samsung 183 L Direct Cool Single Door 4 Star Refrigerator
Samsung 189 L Direct Cool Single Door 5 Star Refrigerator with Base Drawer
Haier 190 L Direct Cool Single Door 4 Star Refrigerator  with Ice Formation possible in 60 Minutes, Ea...
Haier 190 L Direct Cool Single Door 3 Star Refrigerator  with Ice Formation possible in 60 Minutes, Ea...
LG 185 L Direct Cool Single Door 5 Star Refrigerator with Base Drawer  with Smart Inverter Compressor,...
Haier 190 L Direct Cool Single Door 2 Star Refrigerator  with Ice Formation possible in 60 Minutes, Ea...
Haier 190 L Direct Cool Single Door 5 Star Refrigerator with Base Drawer
LG 185 L Direct Cool Single Door 4 Star Refrigerator with Base Drawer  with Smart Inverter Compressor,...
LG 185 L Direct Cool Single Door 5 Star Refrigerator with Base Drawer  with Smart Inverter Compressor,...
Whirlpool 184 L Direct Cool Single Door 2 Star Refrigerator
LG 185 L Direct Cool Single Door 4 Star Refrigerator with Base Drawer  with Smart Inverter Compressor,...
Voltas Beko 183 L Direct Cool Single Door 2 Star Refrigerator
Samsung 215 L Direct Cool Single Door 5 Star Refrigerator with Base Drawer
Samsung 301 L Frost Free Double Door 2 Star Refrigerator
Samsung 419 L Frost Free Double Door 2 Star Refrigerator
Voltas Beko 183 L Direct Cool Single Door 2 Star Refrigerator
Samsung 189 L Direct Cool Single Door 5 Star Refrigerator with Base Drawer
Samsung 330 L Frost Free Double Door 3 Star Refrigerator
Samsung 419 L Frost Free Double Door 3 Star Refrigerator
Haier 190 L Direct Cool Single Door 4 Star Refrigerator with Base Drawer  with Ice Formation possible ...
Haier 165 L Direct Cool Single Door 1 Star Refrigerator  with Diamond Edge Freezing Technology, Easy &...

In [12]:
rating=soup.find("div",attrs={"class":"a7saXW"})

In [13]:
rating

<div class="a7saXW"><span class="CjyrHS" id="productRating_LSTRFRHKCXUMFAVEYQAZPTLNT_RFRHKCXUMFAVEYQA_"><div class="MKiFS6">4.4<img class="PZfbSE" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMiI+PHBhdGggZmlsbD0iI0ZGRiIgZD0iTTYuNSA5LjQzOWwtMy42NzQgMi4yMy45NC00LjI2LTMuMjEtMi44ODMgNC4yNTQtLjQwNEw2LjUuMTEybDEuNjkgNC4wMSA0LjI1NC40MDQtMy4yMSAyLjg4Mi45NCA0LjI2eiIvPjwvc3ZnPg=="/></div></span><span class="PvbNMB"><span><span>4,262 Ratings </span><span class="o2SIOJ">&amp;</span><span> 309 Reviews</span></span></span></div>

In [14]:
productname=[]

for x in soup.find_all('div',attrs={'class':"a7saXW"}):
    productname.append(x.text if x else np.nan)

for name in productname:
    print(name)

4.44,262 Ratings & 309 Reviews
4.44,262 Ratings & 309 Reviews
4.32,579 Ratings & 128 Reviews
4.415,250 Ratings & 897 Reviews
4.536,000 Ratings & 2,251 Reviews
4.49,490 Ratings & 605 Reviews
4.4412 Ratings & 31 Reviews
4.517,459 Ratings & 1,068 Reviews
4.4578 Ratings & 36 Reviews
4.47,300 Ratings & 494 Reviews
4.46,488 Ratings & 373 Reviews
4.53,785 Ratings & 251 Reviews
4.350,308 Ratings & 2,759 Reviews
4.47,351 Ratings & 383 Reviews
4.535 Ratings & 1 Reviews
4.536,000 Ratings & 2,251 Reviews
4.319,806 Ratings & 1,350 Reviews
4.319,806 Ratings & 1,350 Reviews
4.250 Ratings & 2 Reviews
4.536,000 Ratings & 2,251 Reviews
4.319,806 Ratings & 1,350 Reviews
4.319,806 Ratings & 1,350 Reviews
4.414,421 Ratings & 1,049 Reviews
4.24,200 Ratings & 228 Reviews

In [17]:
spefications=soup.find("div",attrs={'class':'CMXw7N'})
spefications

<div class="CMXw7N"><ul class="HwRTzP"><li class="DTBslk">Smart Inverter Compressor</li><li class="DTBslk">Built-in Stabilizer</li><li class="DTBslk">Manufacturer warranty: 1 year comprehensive warranty, 10 years warranty on compressor (T&amp;C apply).Contact Brand for queries/assistance @ [Telephone: 08069379999, WhatsApp: 9711709999 &amp; Email: serviceindia@lge.com] and provide product's model name and seller's details mentioned on your invoice. Brand's service center will allot you a convenient slot for the service. For units installed by entities outside of Brand's service network, warranty repairs for defects attributed to installation may be charged by the Brand.</li></ul></div>

In [18]:
productname=[]

for x in soup.find_all('div',attrs={'class':"CMXw7N"}):
    productname.append(x.text if x else np.nan)

for name in productname:
    print(name)

Smart Inverter CompressorBuilt-in StabilizerManufacturer warranty: 1 year comprehensive warranty, 10 years warranty on compressor (T&C apply).Contact Brand for queries/assistance @ [Telephone: 08069379999, WhatsApp: 9711709999 & Email: serviceindia@lge.com] and provide product's model name and seller's details mentioned on your invoice. Brand's service center will allot you a convenient slot for the service. For units installed by entities outside of Brand's service network, warranty repairs for defects attributed to installation may be charged by the Brand.
Smart Inverter CompressorBuilt-in StabilizerManufacturer warranty: 1 year comprehensive warranty, 10 years warranty on compressor (T&C apply).Contact Brand for queries/assistance @ [Telephone: 08069379999, WhatsApp: 9711709999 & Email: serviceindia@lge.com] and provide product's model name and seller's details mentioned on your invoice. Brand's service center will allot you a convenient slot for the service. For units installed by entities outside of Brand's service network, warranty repairs for defects attributed to installation may be charged by the Brand.
Reciprocatory CompressorBuilt-in Stabilizer5 YEARS FREE COMPREHENSIVE WARRANTY, applicable on purchase from 1st April 2026 (until withdrawn at the sole discretion of the Company). Warranty can be availed after registering on Brand website within 15 days of purchase.
Digital Inverter CompressorBuilt-in Stabilizer1 Year Comprehensive Warranty on product & 10 years Warranty on Digital Inverter Compressor. [20 Year Digital Inverter Compressor Warranty applicable for purchases done only from 1st December 2022 till 31st March 2026]
Digital Inverter CompressorBuilt-in Stabilizer1 Year Comprehensive Warranty on product & 10 years Warranty on Digital Inverter Compressor. [20 Year Digital Inverter Compressor Warranty applicable for purchases done only from 1st December 2022 till 31st March 2026]
Normal CompressorBuilt-in Stabilizer1 Year warranty on Product & 10 Years warranty on Compressor
Normal CompressorBuilt-in Stabilizer1 Year warranty on Product & 10 Years warranty on Compressor
Smart Inverter CompressorBuilt-in StabilizerManufacturer warranty: 1 year comprehensive warranty, 10 years warranty on compressor (T&C apply)
Normal CompressorBuilt-in Stabilizer1 Year warranty on Product & 10 Years warranty on Compressor
Inverter CompressorBuilt-in Stabilizer1 Year warranty on Product & 10 Years warranty on Compressor
Smart Inverter CompressorBuilt-in Stabilizer1 Year on Product and 10 Years on Compressor From Brand
Smart Inverter CompressorBuilt-in StabilizerManufacturer warranty: 1 year comprehensive warranty, 10 years warranty on compressor (T&C apply)
ReciprocatingBuilt-in Stabilizer1 Year Comprehensive Warranty Plus 9 Years Warranty on Compressor
Smart Inverter CompressorBuilt-in Stabilizer1 Year on Product and 10 Years on Compressor From Brand
Reciprocating CompressorBuilt-in Stabilizer1 Year Comprehensive warranty on product and 10 Year Compressor warranty
Digital Inverter CompressorBuilt-in Stabilizer1 Year Comprehensive Warranty on product & 10 years Warranty on Digital Inverter Compressor. [20 Year Digital Inverter Compressor Warranty applicable for purchases done only from 1st December 2022 till 31st March 2026]
Digital Inverter CompressorBuilt-in Stabilizer1 Year Comprehensive Warranty on product & 10 years Warranty on Digital Inverter Compressor. [20 Year Digital Inverter Compressor Warranty applicable for purchases done only from 1st December 2022 till 31st March 2026]
Digital Inverter CompressorBuilt-in Stabilizer1 Year Comprehensive Warranty on product & 10 years Warranty on Digital Inverter Compressor. [20 Year Digital Inverter Compressor Warranty applicable for purchases done only from 1st December 2022 till 31st March 2026]
Reciprocating CompressorBuilt-in Stabilizer1 Year Comprehensive warranty on product and 10 Year Compressor warranty
Digital Inverter CompressorBuilt-in Stabilizer1 Year Comprehensive Warranty on product & 10 years Warranty on Digital Inverter Compressor. [20 Year Digital Inverter Compressor Warranty applicable for purchases done only from 1st December 2022 till 31st March 2026]
Digital Inverter CompressorBuilt-in Stabilizer1 Year Comprehensive Warranty on product & 10 years Warranty on Digital Inverter Compressor. [20 Year Digital Inverter Compressor Warranty applicable for purchases done only from 1st December 2022 till 31st March 2026]
Digital Inverter CompressorBuilt-in Stabilizer1 Year Comprehensive Warranty on product & 10 years Warranty on Digital Inverter Compressor. [20 Year Digital Inverter Compressor Warranty applicable for purchases done only from 1st December 2022 till 31st March 2026]
Normal CompressorBuilt-in Stabilizer1 Year warranty on Product & 10 Years warranty on Compressor
Normal CompressorBuilt-in Stabilizer1 Year warranty on Product & 10 Years warranty on Compressor

In [21]:
price=soup.find("div",attrs={"class":"hZ3P6w DeU9vF"})
price

In [22]:
productname=[]

for x in soup.find_all('div',attrs={'class':"hZ3P6w DeU9vF"}):
    productname.append(x.text if x else np.nan)

for name in productname:
    print(name)

₹14,990
₹14,990
₹11,990
₹16,190
₹18,490
₹14,190
₹13,850
₹18,490
₹12,790
₹16,599
₹17,490
₹17,690
₹12,990
₹17,490
₹12,590
₹20,790
₹35,490
₹48,990
₹11,990
₹18,790
₹39,990
₹50,990
₹15,290
₹10,990

In [23]:
discount=soup.find("div",attrs={'class':"HQe8jr"})
discount

In [24]:
productname=[]

for x in soup.find_all('div',attrs={'class':"HQe8jr"}):
    productname.append(x.text if x else np.nan)

for name in productname:
    print(name)

28% off
28% off
27% off
22% off
22% off
41% off
37% off
29% off
32% off
34% off
28% off
31% off
17% off
28% off
55% off
20% off
22% off
20% off
57% off
21% off
21% off
20% off
40% off
33% off
40% off
28% off
28% off
20% off
32% off

In [25]:
orginalprice=soup.find("div",attrs={'class':"kRYCnD gxR4EY"})
orginalprice

In [26]:
productname=[]

for x in soup.find_all('div',attrs={'class':"kRYCnD gxR4EY"}):
    productname.append(x.text if x else np.nan)

for name in productname:
    print(name)

₹20,890
₹20,890
₹16,490
₹20,999
₹23,999
₹24,390
₹21,990
₹26,290
₹18,990
₹25,290
₹24,490
₹25,690
₹15,800
₹24,490
₹27,990
₹25,999
₹45,999
₹61,999
₹27,990
₹23,999
₹50,999
₹63,999
₹25,590
₹16,590

In [28]:
reviews=soup.find("span",attrs={'class':"PvbNMB"})
reviews

In [29]:
productname=[]

for x in soup.find_all('span',attrs={'class':"PvbNMB"}):
    productname.append(x.text if x else np.nan)

for name in productname:
    print(name)

4,262 Ratings & 309 Reviews
4,262 Ratings & 309 Reviews
2,579 Ratings & 128 Reviews
15,250 Ratings & 897 Reviews
36,000 Ratings & 2,251 Reviews
9,490 Ratings & 605 Reviews
412 Ratings & 31 Reviews
17,459 Ratings & 1,068 Reviews
578 Ratings & 36 Reviews
7,300 Ratings & 494 Reviews
6,488 Ratings & 373 Reviews
3,785 Ratings & 251 Reviews
50,308 Ratings & 2,759 Reviews
7,351 Ratings & 383 Reviews
35 Ratings & 1 Reviews
36,000 Ratings & 2,251 Reviews
19,806 Ratings & 1,350 Reviews
19,806 Ratings & 1,350 Reviews
50 Ratings & 2 Reviews
36,000 Ratings & 2,251 Reviews
19,806 Ratings & 1,350 Reviews
19,806 Ratings & 1,350 Reviews
14,421 Ratings & 1,049 Reviews
4,200 Ratings & 228 Reviews

In [35]:
for i in range (1,93):
    print(f"https://www.flipkart.com/search?q=refrigerator&sid=j9e,abm,hzg&as=on&as-show=on&as-pos=1&as-type=RECENT&as-searchtext=ref&requestId=c5770c84-ccd6-4072-b696-8e25ea970ead&suggestionId=refrigerator%7CRefrigerators&otracker=AS_QueryStore_OrganicAutoSuggest_%7BPOSITION%7D_3_na_na_na&isSearchQuery=true={i}")

https://www.flipkart.com/search?q=refrigerator&sid=j9e,abm,hzg&as=on&as-show=on&as-pos=1&as-type=RECENT&as-searchtext=ref&requestId=c5770c84-ccd6-4072-b696-8e25ea970ead&suggestionId=refrigerator%7CRefrigerators&otracker=AS_QueryStore_OrganicAutoSuggest_%7BPOSITION%7D_3_na_na_na&isSearchQuery=true=1
https://www.flipkart.com/search?q=refrigerator&sid=j9e,abm,hzg&as=on&as-show=on&as-pos=1&as-type=RECENT&as-searchtext=ref&requestId=c5770c84-ccd6-4072-b696-8e25ea970ead&suggestionId=refrigerator%7CRefrigerators&otracker=AS_QueryStore_OrganicAutoSuggest_%7BPOSITION%7D_3_na_na_na&isSearchQuery=true=2
https://www.flipkart.com/search?q=refrigerator&sid=j9e,abm,hzg&as=on&as-show=on&as-pos=1&as-type=RECENT&as-searchtext=ref&requestId=c5770c84-ccd6-4072-b696-8e25ea970ead&suggestionId=refrigerator%7CRefrigerators&otracker=AS_QueryStore_OrganicAutoSuggest_%7BPOSITION%7D_3_na_na_na&isSearchQuery=true=3
https://www.flipkart.com/search?q=refrigerator&sid=j9e,abm,hzg&as=on&as-show=on&as-pos=1&as-type=RECENT&as-searchtext=ref&requestId=c5770c84-ccd6-4072-b696-8e25ea970ead&suggestionId=refrigerator%7CRefrigerators&otracker=AS_QueryStore_OrganicAutoSuggest_%7BPOSITION%7D_3_na_na_na&isSearchQuery=true=4
https://www.flipkart.com/search?q=refrigerator&sid=j9e,abm,hzg&as=on&as-show=on&as-pos=1&as-type=RECENT&as-searchtext=ref&requestId=c5770c84-ccd6-4072-b696-8e25ea970ead&suggestionId=refrigerator%7CRefrigerators&otracker=AS_QueryStore_OrganicAutoSuggest_%7BPOSITION%7D_3_na_na_na&isSearchQuery=true=5
https://www.flipkart.com/search?q=refrigerator&sid=j9e,abm,hzg&as=on&as-show=on&as-pos=1&as-type=RECENT&as-searchtext=ref&requestId=c5770c84-ccd6-4072-b696-8e25ea970ead&suggestionId=refrigerator%7CRefrigerators&otracker=AS_QueryStore_OrganicAutoSuggest_%7BPOSITION%7D_3_na_na_na&isSearchQuery=true=6
https://www.flipkart.com/search?q=refrigerator&sid=j9e,abm,hzg&as=on&as-show=on&as-pos=1&as-type=RECENT&as-searchtext=ref&requestId=c5770c84-ccd6-4072-b696-8e25ea970ead&suggestionId=refrigerator%7CRefrigerators&otracker=AS_QueryStore_OrganicAutoSuggest_%7BPOSITION%7D_3_na_na_na&isSearchQuery=true=7
https://www.flipkart.com/search?q=refrigerator&sid=j9e,abm,hzg&as=on&as-show=on&as-pos=1&as-type=RECENT&as-searchtext=ref&requestId=c5770c84-ccd6-4072-b696-8e25ea970ead&suggestionId=refrigerator%7CRefrigerators&otracker=AS_QueryStore_OrganicAutoSuggest_%7BPOSITION%7D_3_na_na_na&isSearchQuery=true=8
https://www.flipkart.com/search?q=refrigerator&sid=j9e,abm,hzg&as=on&as-show=on&as-pos=1&as-type=RECENT&as-searchtext=ref&requestId=c5770c84-ccd6-4072-b696-8e25ea970ead&suggestionId=refrigerator%7CRefrigerators&otracker=AS_QueryStore_OrganicAutoSuggest_%7BPOSITION%7D_3_na_na_na&isSearchQuery=true=9
https://www.flipkart.com/search?q=refrigerator&sid=j9e,abm,hzg&as=on&as-show=on&as-pos=1&as-type=RECENT&as-searchtext=ref&requestId=c5770c84-ccd6-4072-b696-8e25ea970ead&suggestionId=refrigerator%7CRefrigerators&otracker=AS_QueryStore_OrganicAutoSuggest_%7BPOSITION%7D_3_na_na_na&isSearchQuery=true=10
https://www.flipkart.com/search?q=refrigerator&sid=j9e,abm,hzg&as=on&as-show=on&as-pos=1&as-type=RECENT&as-searchtext=ref&requestId=c5770c84-ccd6-4072-b696-8e25ea970ead&suggestionId=refrigerator%7CRefrigerators&otracker=AS_QueryStore_OrganicAutoSuggest_%7BPOSITION%7D_3_na_na_na&isSearchQuery=true=11
https://www.flipkart.com/search?q=refrigerator&sid=j9e,abm,hzg&as=on&as-show=on&as-pos=1&as-type=RECENT&as-searchtext=ref&requestId=c5770c84-ccd6-4072-b696-8e25ea970ead&suggestionId=refrigerator%7CRefrigerators&otracker=AS_QueryStore_OrganicAutoSuggest_%7BPOSITION%7D_3_na_na_na&isSearchQuery=true=12
https://www.flipkart.com/search?q=refrigerator&sid=j9e,abm,hzg&as=on&as-show=on&as-pos=1&as-type=RECENT&as-searchtext=ref&requestId=c5770c84-ccd6-4072-b696-8e25ea970ead&suggestionId=refrigerator%7CRefrigerators&otracker=AS_QueryStore_OrganicAutoSuggest_%7BPOSITION%7D_3_na_na_na&isSearchQuery=true=13
https://www.flipkart.com/search?q=refrigerator&sid=j9e,abm,hzg&as=on&as-show=on&as-pos=1&as-type=RECENT&as-searchtext=ref&requestId=c5770c84-ccd6-4072-b696-8e25ea970ead&suggestionId=refrigerator%7CRefrigerators&otracker=AS_QueryStore_OrganicAutoSuggest_%7BPOSITION%7D_3_na_na_na&isSearchQuery=true=14
https://www.flipkart.com/search?q=refrigerator&sid=j9e,abm,hzg&as=on&as-show=on&as-pos=1&as-type=RECENT&as-searchtext=ref&requestId=c5770c84-ccd6-4072-b696-8e25ea970ead&suggestionId=refrigerator%7CRefrigerators&otracker=AS_QueryStore_OrganicAutoSuggest_%7BPOSITION%7D_3_na_na_na&isSearchQuery=true=15
https://www.flipkart.com/search?q=refrigerator&sid=j9e,abm,hzg&as=on&as-show=on&as-pos=1&as-type=RECENT&as-searchtext=ref&requestId=c5770c84-ccd6-4072-b696-8e25ea970ead&suggestionId=refrigerator%7CRefrigerators&otracker=AS_QueryStore_OrganicAutoSuggest_%7BPOSITION%7D_3_na_na_na&isSearchQuery=true=16
https://www.flipkart.com/search?q=refrigerator&sid=j9e,abm,hzg&as=on&as-show=on&as-pos=1&as-type=RECENT&as-searchtext=ref&requestId=c5770c84-ccd6-4072-b696-8e25ea970ead&suggestionId=refrigerator%7CRefrigerators&otracker=AS_QueryStore_OrganicAutoSuggest_%7BPOSITION%7D_3_na_na_na&isSearchQuery=true=17
https://www.flipkart.com/search?q=refrigerator&sid=j9e,abm,hzg&as=on&as-show=on&as-pos=1&as-type=RECENT&as-searchtext=ref&requestId=c5770c84-ccd6-4072-b696-8e25ea970ead&suggestionId=refrigerator%7CRefrigerators&otracker=AS_QueryStore_OrganicAutoSuggest_%7BPOSITION%7D_3_na_na_na&isSearchQuery=true=18
https://www.flipkart.com/search?q=refrigerator&sid=j9e,abm,hzg&as=on&as-show=on&as-pos=1&as-type=RECENT&as-searchtext=ref&requestId=c5770c84-ccd6-4072-b696-8e25ea970ead&suggestionId=refrigerator%7CRefrigerators&otracker=AS_QueryStore_OrganicAutoSuggest_%7BPOSITION%7D_3_na_na_na&isSearchQuery=true=19
https://www.flipkart.com/search?q=refrigerator&sid=j9e,abm,hzg&as=on&as-show=on&as-pos=1&as-type=RECENT&as-searchtext=ref&requestId=c5770c84-ccd6-4072-b696-8e25ea970ead&suggestionId=refrigerator%7CRefrigerators&otracker=AS_QueryStore_OrganicAutoSuggest_%7BPOSITION%7D_3_na_na_na&isSearchQuery=true=20
https://www.flipkart.com/search?q=refrigerator&sid=j9e,abm,hzg&as=on&as-show=on&as-pos=1&as-type=RECENT&as-searchtext=ref&requestId=c5770c84-ccd6-4072-b696-8e25ea970ead&suggestionId=refrigerator%7CRefrigerators&otracker=AS_QueryStore_OrganicAutoSuggest_%7BPOSITION%7D_3_na_na_na&isSearchQuery=true=21
https://www.flipkart.com/search?q=refrigerator&sid=j9e,abm,hzg&as=on&as-show=on&as-pos=1&as-type=RECENT&as-searchtext=ref&requestId=c5770c84-ccd6-4072-b696-8e25ea970ead&suggestionId=refrigerator%7CRefrigerators&otracker=AS_QueryStore_OrganicAutoSuggest_%7BPOSITION%7D_3_na_na_na&isSearchQuery=true=22
https://www.flipkart.com/search?q=refrigerator&sid=j9e,abm,hzg&as=on&as-show=on&as-pos=1&as-type=RECENT&as-searchtext=ref&requestId=c5770c84-ccd6-4072-b696-8e25ea970ead&suggestionId=refrigerator%7CRefrigerators&otracker=AS_QueryStore_OrganicAutoSuggest_%7BPOSITION%7D_3_na_na_na&isSearchQuery=true=23
https://www.flipkart.com/search?q=refrigerator&sid=j9e,abm,hzg&as=on&as-show=on&as-pos=1&as-type=RECENT&as-searchtext=ref&requestId=c5770c84-ccd6-4072-b696-8e25ea970ead&suggestionId=refrigerator%7CRefrigerators&otracker=AS_QueryStore_OrganicAutoSuggest_%7BPOSITION%7D_3_na_na_na&isSearchQuery=true=24
https://www.flipkart.com/search?q=refrigerator&sid=j9e,abm,hzg&as=on&as-show=on&as-pos=1&as-type=RECENT&as-searchtext=ref&requestId=c5770c84-ccd6-4072-b696-8e25ea970ead&suggestionId=refrigerator%7CRefrigerators&otracker=AS_QueryStore_OrganicAutoSuggest_%7BPOSITION%7D_3_na_na_na&isSearchQuery=true=25
https://www.flipkart.com/search?q=refrigerator&sid=j9e,abm,hzg&as=on&as-show=on&as-pos=1&as-type=RECENT&as-searchtext=ref&requestId=c5770c84-ccd6-4072-b696-8e25ea970ead&suggestionId=refrigerator%7CRefrigerators&otracker=AS_QueryStore_OrganicAutoSuggest_%7BPOSITION%7D_3_na_na_na&isSearchQuery=true=26
https://www.flipkart.com/search?q=refrigerator&sid=j9e,abm,hzg&as=on&as-show=on&as-pos=1&as-type=RECENT&as-searchtext=ref&requestId=c5770c84-ccd6-4072-b696-8e25ea970ead&suggestionId=refrigerator%7CRefrigerators&otracker=AS_QueryStore_OrganicAutoSuggest_%7BPOSITION%7D_3_na_na_na&isSearchQuery=true=27
https://www.flipkart.com/search?q=refrigerator&sid=j9e,abm,hzg&as=on&as-show=on&as-pos=1&as-type=RECENT&as-searchtext=ref&requestId=c5770c84-ccd6-4072-b696-8e25ea970ead&suggestionId=refrigerator%7CRefrigerators&otracker=AS_QueryStore_OrganicAutoSuggest_%7BPOSITION%7D_3_na_na_na&isSearchQuery=true=28
https://www.flipkart.com/search?q=refrigerator&sid=j9e,abm,hzg&as=on&as-show=on&as-pos=1&as-type=RECENT&as-searchtext=ref&requestId=c5770c84-ccd6-4072-b696-8e25ea970ead&suggestionId=refrigerator%7CRefrigerators&otracker=AS_QueryStore_OrganicAutoSuggest_%7BPOSITION%7D_3_na_na_na&isSearchQuery=true=29
https://www.flipkart.com/search?q=refrigerator&sid=j9e,abm,hzg&as=on&as-show=on&as-pos=1&as-type=RECENT&as-searchtext=ref&requestId=c5770c84-ccd6-4072-b696-8e25ea970ead&suggestionId=refrigerator%7CRefrigerators&otracker=AS_QueryStore_OrganicAutoSuggest_%7BPOSITION%7D_3_na_na_na&isSearchQuery=true=30
https://www.flipkart.com/search?q=refrigerator&sid=j9e,abm,hzg&as=on&as-show=on&as-pos=1&as-type=RECENT&as-searchtext=ref&requestId=c5770c84-ccd6-4072-b696-8e25ea970ead&suggestionId=refrigerator%7CRefrigerators&otracker=AS_QueryStore_OrganicAutoSuggest_%7BPOSITION%7D_3_na_na_na&isSearchQuery=true=31
https://www.flipkart.com/search?q=refrigerator&sid=j9e,abm,hzg&as=on&as-show=on&as-pos=1&as-type=RECENT&as-searchtext=ref&requestId=c5770c84-ccd6-4072-b696-8e25ea970ead&suggestionId=refrigerator%7CRefrigerators&otracker=AS_QueryStore_OrganicAutoSuggest_%7BPOSITION%7D_3_na_na_na&isSearchQuery=true=32
https://www.flipkart.com/search?q=refrigerator&sid=j9e,abm,hzg&as=on&as-show=on&as-pos=1&as-type=RECENT&as-searchtext=ref&requestId=c5770c84-ccd6-4072-b696-8e25ea970ead&suggestionId=refrigerator%7CRefrigerators&otracker=AS_QueryStore_OrganicAutoSuggest_%7BPOSITION%7D_3_na_na_na&isSearchQuery=true=33
https://www.flipkart.com/search?q=refrigerator&sid=j9e,abm,hzg&as=on&as-show=on&as-pos=1&as-type=RECENT&as-searchtext=ref&requestId=c5770c84-ccd6-4072-b696-8e25ea970ead&suggestionId=refrigerator%7CRefrigerators&otracker=AS_QueryStore_OrganicAutoSuggest_%7BPOSITION%7D_3_na_na_na&isSearchQuery=true=34
https://www.flipkart.com/search?q=refrigerator&sid=j9e,abm,hzg&as=on&as-show=on&as-pos=1&as-type=RECENT&as-searchtext=ref&requestId=c5770c84-ccd6-4072-b696-8e25ea970ead&suggestionId=refrigerator%7CRefrigerators&otracker=AS_QueryStore_OrganicAutoSuggest_%7BPOSITION%7D_3_na_na_na&isSearchQuery=true=35
https://www.flipkart.com/search?q=refrigerator&sid=j9e,abm,hzg&as=on&as-show=on&as-pos=1&as-type=RECENT&as-searchtext=ref&requestId=c5770c84-ccd6-4072-b696-8e25ea970ead&suggestionId=refrigerator%7CRefrigerators&otracker=AS_QueryStore_OrganicAutoSuggest_%7BPOSITION%7D_3_na_na_na&isSearchQuery=true=36
https://www.flipkart.com/search?q=refrigerator&sid=j9e,abm,hzg&as=on&as-show=on&as-pos=1&as-type=RECENT&as-searchtext=ref&requestId=c5770c84-ccd6-4072-b696-8e25ea970ead&suggestionId=refrigerator%7CRefrigerators&otracker=AS_QueryStore_OrganicAutoSuggest_%7BPOSITION%7D_3_na_na_na&isSearchQuery=true=37
https://www.flipkart.com/search?q=refrigerator&sid=j9e,abm,hzg&as=on&as-show=on&as-pos=1&as-type=RECENT&as-searchtext=ref&requestId=c5770c84-ccd6-4072-b696-8e25ea970ead&suggestionId=refrigerator%7CRefrigerators&otracker=AS_QueryStore_OrganicAutoSuggest_%7BPOSITION%7D_3_na_na_na&isSearchQuery=true=38
https://www.flipkart.com/search?q=refrigerator&sid=j9e,abm,hzg&as=on&as-show=on&as-pos=1&as-type=RECENT&as-searchtext=ref&requestId=c5770c84-ccd6-4072-b696-8e25ea970ead&suggestionId=refrigerator%7CRefrigerators&otracker=AS_QueryStore_OrganicAutoSuggest_%7BPOSITION%7D_3_na_na_na&isSearchQuery=true=39
https://www.flipkart.com/search?q=refrigerator&sid=j9e,abm,hzg&as=on&as-show=on&as-pos=1&as-type=RECENT&as-searchtext=ref&requestId=c5770c84-ccd6-4072-b696-8e25ea970ead&suggestionId=refrigerator%7CRefrigerators&otracker=AS_QueryStore_OrganicAutoSuggest_%7BPOSITION%7D_3_na_na_na&isSearchQuery=true=40
https://www.flipkart.com/search?q=refrigerator&sid=j9e,abm,hzg&as=on&as-show=on&as-pos=1&as-type=RECENT&as-searchtext=ref&requestId=c5770c84-ccd6-4072-b696-8e25ea970ead&suggestionId=refrigerator%7CRefrigerators&otracker=AS_QueryStore_OrganicAutoSuggest_%7BPOSITION%7D_3_na_na_na&isSearchQuery=true=41
https://www.flipkart.com/search?q=refrigerator&sid=j9e,abm,hzg&as=on&as-show=on&as-pos=1&as-type=RECENT&as-searchtext=ref&requestId=c5770c84-ccd6-4072-b696-8e25ea970ead&suggestionId=refrigerator%7CRefrigerators&otracker=AS_QueryStore_OrganicAutoSuggest_%7BPOSITION%7D_3_na_na_na&isSearchQuery=true=42
https://www.flipkart.com/search?q=refrigerator&sid=j9e,abm,hzg&as=on&as-show=on&as-pos=1&as-type=RECENT&as-searchtext=ref&requestId=c5770c84-ccd6-4072-b696-8e25ea970ead&suggestionId=refrigerator%7CRefrigerators&otracker=AS_QueryStore_OrganicAutoSuggest_%7BPOSITION%7D_3_na_na_na&isSearchQuery=true=43
https://www.flipkart.com/search?q=refrigerator&sid=j9e,abm,hzg&as=on&as-show=on&as-pos=1&as-type=RECENT&as-searchtext=ref&requestId=c5770c84-ccd6-4072-b696-8e25ea970ead&suggestionId=refrigerator%7CRefrigerators&otracker=AS_QueryStore_OrganicAutoSuggest_%7BPOSITION%7D_3_na_na_na&isSearchQuery=true=44
https://www.flipkart.com/search?q=refrigerator&sid=j9e,abm,hzg&as=on&as-show=on&as-pos=1&as-type=RECENT&as-searchtext=ref&requestId=c5770c84-ccd6-4072-b696-8e25ea970ead&suggestionId=refrigerator%7CRefrigerators&otracker=AS_QueryStore_OrganicAutoSuggest_%7BPOSITION%7D_3_na_na_na&isSearchQuery=true=45
https://www.flipkart.com/search?q=refrigerator&sid=j9e,abm,hzg&as=on&as-show=on&as-pos=1&as-type=RECENT&as-searchtext=ref&requestId=c5770c84-ccd6-4072-b696-8e25ea970ead&suggestionId=refrigerator%7CRefrigerators&otracker=AS_QueryStore_OrganicAutoSuggest_%7BPOSITION%7D_3_na_na_na&isSearchQuery=true=46
https://www.flipkart.com/search?q=refrigerator&sid=j9e,abm,hzg&as=on&as-show=on&as-pos=1&as-type=RECENT&as-searchtext=ref&requestId=c5770c84-ccd6-4072-b696-8e25ea970ead&suggestionId=refrigerator%7CRefrigerators&otracker=AS_QueryStore_OrganicAutoSuggest_%7BPOSITION%7D_3_na_na_na&isSearchQuery=true=47
https://www.flipkart.com/search?q=refrigerator&sid=j9e,abm,hzg&as=on&as-show=on&as-pos=1&as-type=RECENT&as-searchtext=ref&requestId=c5770c84-ccd6-4072-b696-8e25ea970ead&suggestionId=refrigerator%7CRefrigerators&otracker=AS_QueryStore_OrganicAutoSuggest_%7BPOSITION%7D_3_na_na_na&isSearchQuery=true=48
https://www.flipkart.com/search?q=refrigerator&sid=j9e,abm,hzg&as=on&as-show=on&as-pos=1&as-type=RECENT&as-searchtext=ref&requestId=c5770c84-ccd6-4072-b696-8e25ea970ead&suggestionId=refrigerator%7CRefrigerators&otracker=AS_QueryStore_OrganicAutoSuggest_%7BPOSITION%7D_3_na_na_na&isSearchQuery=true=49
https://www.flipkart.com/search?q=refrigerator&sid=j9e,abm,hzg&as=on&as-show=on&as-pos=1&as-type=RECENT&as-searchtext=ref&requestId=c5770c84-ccd6-4072-b696-8e25ea970ead&suggestionId=refrigerator%7CRefrigerators&otracker=AS_QueryStore_OrganicAutoSuggest_%7BPOSITION%7D_3_na_na_na&isSearchQuery=true=50
https://www.flipkart.com/search?q=refrigerator&sid=j9e,abm,hzg&as=on&as-show=on&as-pos=1&as-type=RECENT&as-searchtext=ref&requestId=c5770c84-ccd6-4072-b696-8e25ea970ead&suggestionId=refrigerator%7CRefrigerators&otracker=AS_QueryStore_OrganicAutoSuggest_%7BPOSITION%7D_3_na_na_na&isSearchQuery=true=51
https://www.flipkart.com/search?q=refrigerator&sid=j9e,abm,hzg&as=on&as-show=on&as-pos=1&as-type=RECENT&as-searchtext=ref&requestId=c5770c84-ccd6-4072-b696-8e25ea970ead&suggestionId=refrigerator%7CRefrigerators&otracker=AS_QueryStore_OrganicAutoSuggest_%7BPOSITION%7D_3_na_na_na&isSearchQuery=true=52
https://www.flipkart.com/search?q=refrigerator&sid=j9e,abm,hzg&as=on&as-show=on&as-pos=1&as-type=RECENT&as-searchtext=ref&requestId=c5770c84-ccd6-4072-b696-8e25ea970ead&suggestionId=refrigerator%7CRefrigerators&otracker=AS_QueryStore_OrganicAutoSuggest_%7BPOSITION%7D_3_na_na_na&isSearchQuery=true=53
https://www.flipkart.com/search?q=refrigerator&sid=j9e,abm,hzg&as=on&as-show=on&as-pos=1&as-type=RECENT&as-searchtext=ref&requestId=c5770c84-ccd6-4072-b696-8e25ea970ead&suggestionId=refrigerator%7CRefrigerators&otracker=AS_QueryStore_OrganicAutoSuggest_%7BPOSITION%7D_3_na_na_na&isSearchQuery=true=54
https://www.flipkart.com/search?q=refrigerator&sid=j9e,abm,hzg&as=on&as-show=on&as-pos=1&as-type=RECENT&as-searchtext=ref&requestId=c5770c84-ccd6-4072-b696-8e25ea970ead&suggestionId=refrigerator%7CRefrigerators&otracker=AS_QueryStore_OrganicAutoSuggest_%7BPOSITION%7D_3_na_na_na&isSearchQuery=true=55
https://www.flipkart.com/search?q=refrigerator&sid=j9e,abm,hzg&as=on&as-show=on&as-pos=1&as-type=RECENT&as-searchtext=ref&requestId=c5770c84-ccd6-4072-b696-8e25ea970ead&suggestionId=refrigerator%7CRefrigerators&otracker=AS_QueryStore_OrganicAutoSuggest_%7BPOSITION%7D_3_na_na_na&isSearchQuery=true=56
https://www.flipkart.com/search?q=refrigerator&sid=j9e,abm,hzg&as=on&as-show=on&as-pos=1&as-type=RECENT&as-searchtext=ref&requestId=c5770c84-ccd6-4072-b696-8e25ea970ead&suggestionId=refrigerator%7CRefrigerators&otracker=AS_QueryStore_OrganicAutoSuggest_%7BPOSITION%7D_3_na_na_na&isSearchQuery=true=57
https://www.flipkart.com/search?q=refrigerator&sid=j9e,abm,hzg&as=on&as-show=on&as-pos=1&as-type=RECENT&as-searchtext=ref&requestId=c5770c84-ccd6-4072-b696-8e25ea970ead&suggestionId=refrigerator%7CRefrigerators&otracker=AS_QueryStore_OrganicAutoSuggest_%7BPOSITION%7D_3_na_na_na&isSearchQuery=true=58
https://www.flipkart.com/search?q=refrigerator&sid=j9e,abm,hzg&as=on&as-show=on&as-pos=1&as-type=RECENT&as-searchtext=ref&requestId=c5770c84-ccd6-4072-b696-8e25ea970ead&suggestionId=refrigerator%7CRefrigerators&otracker=AS_QueryStore_OrganicAutoSuggest_%7BPOSITION%7D_3_na_na_na&isSearchQuery=true=59
https://www.flipkart.com/search?q=refrigerator&sid=j9e,abm,hzg&as=on&as-show=on&as-pos=1&as-type=RECENT&as-searchtext=ref&requestId=c5770c84-ccd6-4072-b696-8e25ea970ead&suggestionId=refrigerator%7CRefrigerators&otracker=AS_QueryStore_OrganicAutoSuggest_%7BPOSITION%7D_3_na_na_na&isSearchQuery=true=60
https://www.flipkart.com/search?q=refrigerator&sid=j9e,abm,hzg&as=on&as-show=on&as-pos=1&as-type=RECENT&as-searchtext=ref&requestId=c5770c84-ccd6-4072-b696-8e25ea970ead&suggestionId=refrigerator%7CRefrigerators&otracker=AS_QueryStore_OrganicAutoSuggest_%7BPOSITION%7D_3_na_na_na&isSearchQuery=true=61
https://www.flipkart.com/search?q=refrigerator&sid=j9e,abm,hzg&as=on&as-show=on&as-pos=1&as-type=RECENT&as-searchtext=ref&requestId=c5770c84-ccd6-4072-b696-8e25ea970ead&suggestionId=refrigerator%7CRefrigerators&otracker=AS_QueryStore_OrganicAutoSuggest_%7BPOSITION%7D_3_na_na_na&isSearchQuery=true=62
https://www.flipkart.com/search?q=refrigerator&sid=j9e,abm,hzg&as=on&as-show=on&as-pos=1&as-type=RECENT&as-searchtext=ref&requestId=c5770c84-ccd6-4072-b696-8e25ea970ead&suggestionId=refrigerator%7CRefrigerators&otracker=AS_QueryStore_OrganicAutoSuggest_%7BPOSITION%7D_3_na_na_na&isSearchQuery=true=63
https://www.flipkart.com/search?q=refrigerator&sid=j9e,abm,hzg&as=on&as-show=on&as-pos=1&as-type=RECENT&as-searchtext=ref&requestId=c5770c84-ccd6-4072-b696-8e25ea970ead&suggestionId=refrigerator%7CRefrigerators&otracker=AS_QueryStore_OrganicAutoSuggest_%7BPOSITION%7D_3_na_na_na&isSearchQuery=true=64
https://www.flipkart.com/search?q=refrigerator&sid=j9e,abm,hzg&as=on&as-show=on&as-pos=1&as-type=RECENT&as-searchtext=ref&requestId=c5770c84-ccd6-4072-b696-8e25ea970ead&suggestionId=refrigerator%7CRefrigerators&otracker=AS_QueryStore_OrganicAutoSuggest_%7BPOSITION%7D_3_na_na_na&isSearchQuery=true=65
https://www.flipkart.com/search?q=refrigerator&sid=j9e,abm,hzg&as=on&as-show=on&as-pos=1&as-type=RECENT&as-searchtext=ref&requestId=c5770c84-ccd6-4072-b696-8e25ea970ead&suggestionId=refrigerator%7CRefrigerators&otracker=AS_QueryStore_OrganicAutoSuggest_%7BPOSITION%7D_3_na_na_na&isSearchQuery=true=66

In [37]:
from bs4 import BeautifulSoup
import requests
import numpy as np
import time

productname = [] 
price = []
rating = []
features = []
pagenum = []
original_price = []
Discount = []
Review = []

headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0 Safari/537.36"
}

total_time = time.time()

for i in range(1,106): 
    start_time = time.time()

    URL = f"https://www.flipkart.com/search?q=refrigerator&sid=j9e,abm,hzg&as=on&as-show=on&as-pos=1&as-type=RECENT&as-searchtext=ref&requestId=c5770c84-ccd6-4072-b696-8e25ea970ead&suggestionId=refrigerator%7CRefrigerators&otracker=AS_QueryStore_OrganicAutoSuggest_%7BPOSITION%7D_3_na_na_na&isSearchQuery=true={i}"

    page = requests.get(URL, headers=headers)   # headers added here
    soup = BeautifulSoup(page.text, "html.parser")

    for x in soup.find_all('div', attrs={'class':'ZFwe0M row'}):
        pname = x.find('div', attrs={'class':'RG5Slk'})
        cost = x.find('div', attrs={'class':'hZ3P6w DeU9vF'})
        rat = x.find('div', attrs={'class':'MKiFS6'})
        specs = x.find('div', attrs={'class':'CMXw7N'})
        op = x.find('div', attrs={'class':'kRYCnD gxR4EY'})
        discount = x.find('div', attrs={'class':'HQe8jr'})
        reviews = x.find('span', attrs={'class':'PvbNMB'})
        
        productname.append(pname.text if pname else np.nan)
        price.append(cost.text if cost else np.nan)
        rating.append(rat.text if rat else np.nan)
        features.append(specs.text if specs else np.nan)
        original_price.append(op.text if op else np.nan)
        Discount.append(discount.text if discount else np.nan)
        Review.append(reviews.text if reviews else np.nan)
        
        pagenum.append(i)

    print(f'Page {i} completed in {time.time()-start_time:.2f} seconds')

print("Total Time Completed in seconds", str(time.time()-total_time))

Page 1 completed in 1.08 seconds
Page 2 completed in 1.14 seconds
Page 3 completed in 0.97 seconds
Page 4 completed in 1.23 seconds
Page 5 completed in 1.36 seconds
Page 6 completed in 1.06 seconds
Page 7 completed in 1.08 seconds
Page 8 completed in 1.07 seconds
Page 9 completed in 1.06 seconds
Page 10 completed in 1.77 seconds
Page 11 completed in 1.11 seconds
Page 12 completed in 1.19 seconds
Page 13 completed in 1.08 seconds
Page 14 completed in 1.04 seconds
Page 15 completed in 0.94 seconds
Page 16 completed in 1.09 seconds
Page 17 completed in 1.02 seconds
Page 18 completed in 1.02 seconds
Page 19 completed in 1.19 seconds
Page 20 completed in 1.14 seconds
Page 21 completed in 1.06 seconds
Page 22 completed in 1.05 seconds
Page 23 completed in 1.33 seconds
Page 24 completed in 1.12 seconds
Page 25 completed in 1.08 seconds
Page 26 completed in 1.27 seconds
Page 27 completed in 1.05 seconds
Page 28 completed in 0.94 seconds
Page 29 completed in 1.16 seconds
Page 30 completed in 1.11 seconds
Page 31 completed in 0.99 seconds
Page 32 completed in 0.95 seconds
Page 33 completed in 0.97 seconds
Page 34 completed in 2.16 seconds
Page 35 completed in 1.10 seconds
Page 36 completed in 0.91 seconds
Page 37 completed in 0.96 seconds
Page 38 completed in 1.09 seconds
Page 39 completed in 1.01 seconds
Page 40 completed in 0.91 seconds
Page 41 completed in 0.96 seconds
Page 42 completed in 0.89 seconds
Page 43 completed in 0.94 seconds
Page 44 completed in 1.23 seconds
Page 45 completed in 1.03 seconds
Page 46 completed in 0.95 seconds
Page 47 completed in 0.96 seconds
Page 48 completed in 0.87 seconds
Page 49 completed in 0.87 seconds
Page 50 completed in 0.92 seconds
Page 51 completed in 0.95 seconds
Page 52 completed in 0.86 seconds
Page 53 completed in 1.00 seconds
Page 54 completed in 0.96 seconds
Page 55 completed in 0.85 seconds
Page 56 completed in 0.97 seconds
Page 57 completed in 1.12 seconds
Page 58 completed in 0.88 seconds
Page 59 completed in 0.96 seconds
Page 60 completed in 1.03 seconds
Page 61 completed in 0.92 seconds
Page 62 completed in 0.94 seconds
Page 63 completed in 0.94 seconds
Page 64 completed in 0.89 seconds
Page 65 completed in 1.12 seconds
Page 66 completed in 0.89 seconds
Page 67 completed in 0.87 seconds
Page 68 completed in 0.88 seconds
Page 69 completed in 0.84 seconds
Page 70 completed in 0.89 seconds
Page 71 completed in 0.87 seconds
Page 72 completed in 0.97 seconds
Page 73 completed in 0.93 seconds
Page 74 completed in 0.94 seconds
Page 75 completed in 1.05 seconds
Page 76 completed in 0.90 seconds
Page 77 completed in 0.91 seconds
Page 78 completed in 1.07 seconds
Page 79 completed in 1.03 seconds
Page 80 completed in 1.14 seconds
Page 81 completed in 1.08 seconds
Page 82 completed in 0.98 seconds
Page 83 completed in 1.25 seconds
Page 84 completed in 1.20 seconds
Page 85 completed in 0.90 seconds
Page 86 completed in 1.23 seconds
Page 87 completed in 1.07 seconds
Page 88 completed in 0.99 seconds
Page 89 completed in 0.91 seconds
Page 90 completed in 0.87 seconds
Page 91 completed in 0.90 seconds
Page 92 completed in 1.28 seconds
Page 93 completed in 0.96 seconds
Page 94 completed in 0.93 seconds
Page 95 completed in 0.89 seconds
Page 96 completed in 1.04 seconds
Page 97 completed in 0.86 seconds
Page 98 completed in 1.05 seconds
Page 99 completed in 0.89 seconds
Page 100 completed in 0.97 seconds
Page 101 completed in 1.06 seconds
Page 102 completed in 1.01 seconds
Page 103 completed in 0.89 seconds
Page 104 completed in 0.97 seconds
Page 105 completed in 0.91 seconds
Total Time Completed in seconds 108.1741886138916

In [38]:
df = pd.DataFrame({
    "Product Name": productname,
    "Price": price,
    "Original Price": original_price,
    "Discount": Discount,
    "Rating": rating,
    "Reviews": Review,
    "Features": features,
    "Page Number": pagenum
})

In [39]:
df

,Product Name,Price,Original Price,Discount,Rating,Reviews,Features,Page Number
0,LG 185 L Direct Cool Single Door 5 Star Refrig...,"₹18,490","₹26,290",29% off,4.5,"17,459 Ratings & 1,068 Reviews",Smart Inverter CompressorBuilt-in StabilizerMa...,1
1,LG 185 L Direct Cool Single Door 5 Star Refrig...,"₹18,290","₹26,290",30% off,4.5,"6,390 Ratings & 467 Reviews",Smart Inverter CompressorBuilt-in StabilizerMa...,1
2,Godrej 180 L Direct Cool Single Door 1 Star Re...,"₹11,990","₹16,490",27% off,4.3,"2,579 Ratings & 128 Reviews",Reciprocatory CompressorBuilt-in Stabilizer5 Y...,1
3,Samsung 183 L Direct Cool Single Door 4 Star R...,"₹16,190","₹20,999",22% off,4.4,"15,250 Ratings & 897 Reviews",Digital Inverter CompressorBuilt-in Stabilizer...,1
4,Samsung 189 L Direct Cool Single Door 5 Star R...,"₹18,490","₹23,999",22% off,4.5,"36,000 Ratings & 2,251 Reviews",Digital Inverter CompressorBuilt-in Stabilizer...,1
...,...,...,...,...,...,...,...,...
2515,Samsung 189 L Direct Cool Single Door 5 Star R...,"₹18,790","₹23,999",21% off,4.5,"36,000 Ratings & 2,251 Reviews",Digital Inverter CompressorBuilt-in Stabilizer...,105
2516,Samsung 330 L Frost Free Double Door 2 Star Re...,"₹37,990","₹48,999",22% off,4.3,"19,806 Ratings & 1,350 Reviews",Digital Inverter CompressorBuilt-in Stabilizer...,105
2517,Samsung 350 L Frost Free Double Door 2 Star Re...,"₹38,990","₹48,999",20% off,4.3,"19,806 Ratings & 1,350 Reviews",Digital Inverter CompressorBuilt-in Stabilizer...,105
2518,Haier 190 L Direct Cool Single Door 4 Star Ref...,"₹15,290","₹25,590",40% off,4.4,"14,421 Ratings & 1,049 Reviews",Normal CompressorBuilt-in Stabilizer1 Year war...,105
2519,Haier 165 L Direct Cool Single Door 1 Star Ref...,"₹10,990","₹16,590",33% off,4.2,"4,200 Ratings & 228 Reviews",Normal CompressorBuilt-in Stabilizer1 Year war...,105

In [41]:
df.to_csv("Refrigerator.csv",index=False)

In [42]:
df=pd.read_csv("Refrigerator.csv")

In [43]:
df

,Product Name,Price,Original Price,Discount,Rating,Reviews,Features,Page Number
0,LG 185 L Direct Cool Single Door 5 Star Refrig...,"₹18,490","₹26,290",29% off,4.5,"17,459 Ratings & 1,068 Reviews",Smart Inverter CompressorBuilt-in StabilizerMa...,1
1,LG 185 L Direct Cool Single Door 5 Star Refrig...,"₹18,290","₹26,290",30% off,4.5,"6,390 Ratings & 467 Reviews",Smart Inverter CompressorBuilt-in StabilizerMa...,1
2,Godrej 180 L Direct Cool Single Door 1 Star Re...,"₹11,990","₹16,490",27% off,4.3,"2,579 Ratings & 128 Reviews",Reciprocatory CompressorBuilt-in Stabilizer5 Y...,1
3,Samsung 183 L Direct Cool Single Door 4 Star R...,"₹16,190","₹20,999",22% off,4.4,"15,250 Ratings & 897 Reviews",Digital Inverter CompressorBuilt-in Stabilizer...,1
4,Samsung 189 L Direct Cool Single Door 5 Star R...,"₹18,490","₹23,999",22% off,4.5,"36,000 Ratings & 2,251 Reviews",Digital Inverter CompressorBuilt-in Stabilizer...,1
...,...,...,...,...,...,...,...,...
2515,Samsung 189 L Direct Cool Single Door 5 Star R...,"₹18,790","₹23,999",21% off,4.5,"36,000 Ratings & 2,251 Reviews",Digital Inverter CompressorBuilt-in Stabilizer...,105
2516,Samsung 330 L Frost Free Double Door 2 Star Re...,"₹37,990","₹48,999",22% off,4.3,"19,806 Ratings & 1,350 Reviews",Digital Inverter CompressorBuilt-in Stabilizer...,105
2517,Samsung 350 L Frost Free Double Door 2 Star Re...,"₹38,990","₹48,999",20% off,4.3,"19,806 Ratings & 1,350 Reviews",Digital Inverter CompressorBuilt-in Stabilizer...,105
2518,Haier 190 L Direct Cool Single Door 4 Star Ref...,"₹15,290","₹25,590",40% off,4.4,"14,421 Ratings & 1,049 Reviews",Normal CompressorBuilt-in Stabilizer1 Year war...,105
2519,Haier 165 L Direct Cool Single Door 1 Star Ref...,"₹10,990","₹16,590",33% off,4.2,"4,200 Ratings & 228 Reviews",Normal CompressorBuilt-in Stabilizer1 Year war...,105